apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-pusher
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-status
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods/log", "pods/status"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-pusher-pod-status-binding
subjects:
- kind: ServiceAccount
  name: metrics-pusher
  namespace: default
roleRef:
  kind: Role
  name: pod-status
  apiGroup: ""
