apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-dispatcher
  labels:
    app: benchmark-ai
spec:
  selector:
    matchLabels:
      app: benchmark-ai
  replicas: 1
  template:

    spec:
      serviceAccountName: fetcher-dispatcher
      affinity:
      #--
      nodeSelector:
      #--

