apiVersion: v1
kind: ConfigMap
metadata:
  name: data
  namespace: default
data:
  big-file: Huge file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataserver
spec:
  selector:
    matchLabels:
        run: dataserver
  replicas: 1
  template:
    metadata:
        labels:
          run: dataserver
    spec:
      containers:
      - name: http-server
        image: trinitronx/python-simplehttpserver
        ports:
        - containerPort: 8080
          volumes:
        volumeMounts:
          - name: data-volume
            mountPath: /var/www
            readOnly: true
      volumes:
      - name: data-volume
        configMap:
          defaultMode: 0700
          name: data
---
apiVersion: v1
kind: Service
metadata:
  name: dataserver
  labels:
    run: dataserver
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: dataserver
