name: watcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.7.*
  - kazoo 2.5.*
  - boto3 1.9.*
  - python-kubernetes 9.0.*
  - pycurl 7.43.*
  - kafka-python 1.4.6
  - python-crontab >= 2.3
  - pip
  - pip:
      - dataclasses-json
      - ConfigArgParse==0.15.1
      - dacite
