apiVersion: batch/v1
kind: Job
metadata:
  name: fetcher-it
spec:
  template:
    spec:
      containers:
        - name: it
          imagePullPolicy: Never
          image: benchmarkai/fetcher-it:local-latest
