version: 0.2

phases:
  install:
    commands:
      - cat $(which start-dind.sh)
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 bash -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - cat $(which start-dind.sh)
      - echo imok
      #- dind-cluster-v1.12.sh up | tee /cluster.log
      #- cd fetcher
      #- make deploy STAGE=local LOCAL_DEPLOY="./deploy/dind_push_image.sh kube-node-1 " | tee /build.log
      #- kubectl get pods
      #- sleep 30s
      #- kubectl get pods > /somefile1.txt
      #- sleep 10s
      #- kubectl get pods > /somefile2.txt
      #- docker ps | tee /it.log
      #- make integration_tests STAGE=local LOCAL_DEPLOY="../deploy/dind_push_image.sh kube-node-1 " | tee /it.log
artifacts:
  #!!!!
  files:
    - /somefile1.txt
    - /somefile2.txt
    - /it.log
    - /dind.log
    - /cluster.log
    - /build.log
  name: getpodsoutput