apiVersion: v1
kind: ServiceAccount
metadata:
  name: fetcher-dispatcher
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-status
  namespace: default
rules:
- apiGroups: [""]
  resources: ["jobs"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fetcher-dispatcher-pod-status-binding
subjects:
- kind: ServiceAccount
  name: fetcher-dispatcher
  namespace: default
roleRef:
  kind: Role
  name: pod-status
  apiGroup: ""