apiVersion: batch/v1
kind: Job
metadata:
  name: {job_id}
  labels:
    app: benchmark-ai
    action-id: {event.action_id}
    parent-action-id: '{event.parent_action_id}'
    client-id: {event.client_id}
    created-by: {service_name}
spec:
  template:
    metadata:
      labels:
        app: benchmark-ai
        action-id: {event.action_id}
        parent-action-id: '{event.parent_action_id}'
        client-id: {event.client_id}
        created-by: {service_name}
      annotations:
        iam.amazonaws.com/role: benchmark-host
    spec:
      serviceAccountName: metrics-pusher
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - benchmark-ai
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: data-puller
        image: {config.puller_docker_image}
        volumeMounts:
        - name: datasets-volume
          mountPath: /data
      - name: script-puller
        image: {config.puller_docker_image}
        volumeMounts:
          - name: scripts-volume
            mountPath: /bai/scripts
      containers:
      - name: benchmark
        image: {descriptor.docker_image}
        resources:
          limits:
            nvidia.com/gpu: {descriptor.gpus_per_instance}
        command: []
        args: []
        securityContext:
          privileged: {descriptor.privileged}
        env:
        - name: BENCHMARK_AI
          value: "fifo"
        - name: BENCHMARK_AI_FIFO_FILEPATH
          value: "/tmp/benchmark-ai/fifo"
        - name: BENCHMARK_AI_FIFO_MAX_WAIT_TIME
          value: "60"
        volumeMounts:
        - mountPath: /tmp/benchmark-ai
          name: benchmark-ai
        - mountPath: /bai/scripts
          name: scripts-volume
      - name: sidecar
        image: {config.metrics_pusher_docker_image}
        env:
        - name: BENCHMARK_AI_FIFO_FILEPATH
          value: /tmp/benchmark-ai/fifo
        ##################################
        # Sidecar backend: Elasticsearch #
        ##################################
#        - name: BACKEND
#          value: elasticsearch
#        - name: BACKEND_ARG_JOB_ID
#          value: {job_id}
#        - name: BACKEND_ARG_HOSTNAME
#          valueFrom:
#            configMapKeyRef:
#              name: outputs-infrastructure
#              key: es_endpoint
#        - name: BACKEND_ARG_PORT
#          value: "443"

        ##########################
        # Sidecar backend: Kafka #
        ##########################
        - name: BACKEND
          value: kafka
        - name: BACKEND_ARG_JOB_ID
          value: {job_id}
        - name: BACKEND_ARG_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: outputs-infrastructure
              key: msk_bootstrap_brokers
        - name: BACKEND_ARG_KEY
          value: {event.client_id}
        - name: BACKEND_ARG_TOPIC
          value: BAI_METRICS
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /tmp/benchmark-ai
          name: benchmark-ai
      nodeSelector:
        beta.kubernetes.io/instance-type: {descriptor.instance_type}
        node.type: bai-worker
        failure-domain.beta.kubernetes.io/zone: {availability_zone}
      restartPolicy: Never
      volumes:
      - name: benchmark-ai
        emptyDir: {{}}
      - name: datasets-volume
        emptyDir: {{}}
      - name: scripts-volume
        emptyDir: {{}}
  backoffLimit: 4
