apiVersion: batch/v1
kind: Job
metadata:
  name: {job_id}
spec:
  template:
    metadata:
      labels:
        app: benchmark-ai
        action-id: {event.action_id}
        client-id: {event.client_id}
        created-by: {service_name}
    spec:
      serviceAccountName: metrics-pusher
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - benchmark-ai
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: data-puller
        volumeMounts:
        - name: datasets-volume
          mountPath: /data
      containers:
      - name: benchmark
        image: {descriptor.docker_image}
        resources:
          limits:
            nvidia.com/gpu: {num_gpus}
        command: []
        args: []
        securityContext:
          privileged: {descriptor.privileged}
        env:
        - name: BENCHMARK_AI
          value: "fifo"
        - name: BENCHMARK_AI_FIFO_FILEPATH
          value: "/tmp/benchmark-ai/fifo"
        - name: BENCHMARK_AI_FIFO_MAX_WAIT_TIME
          value: "60"
        volumeMounts:
        - mountPath: /tmp/benchmark-ai
          name: benchmark-ai
      - name: sidecar
        # TODO: Automate tag selection
        image: benchmarkai/metrics-pusher:ffed580
        env:
        - name: BENCHMARK_AI_FIFO_FILEPATH
          value: /tmp/benchmark-ai/fifo
        - name: BACKEND
          value: elasticsearch
        - name: BACKEND_ARG_JOB_ID
          value: {job_id}
        - name: BACKEND_ARG_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: outputs-infrastructure
              key: es_endpoint
        - name: BACKEND_ARG_PORT
          value: "443"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - mountPath: /tmp/benchmark-ai
          name: benchmark-ai
      nodeSelector:
        beta.kubernetes.io/instance-type: {descriptor.instance_type}
        node.type: bai-worker
        failure-domain.beta.kubernetes.io/zone: {availability_zone}
      restartPolicy: Never
      volumes:
      - name: benchmark-ai
        emptyDir: {{}}
      - name: datasets-volume
        emptyDir: {{}}
  backoffLimit: 4
