name: kafka-utils
channels:
  - conda-forge
  - defaults
dependencies:
  - kazoo 2.5.*
  - kafka-python 1.4.6
  - boto3 1.9.*
  - pycurl 7.43.*
  - timeout-decorator
  - pip
  - python-kubernetes 9.0.*
  - python-crontab >= 2.3
  - addict 2.2.*
  - rfc3987 >= v1.3.8
  - toml 0.9.*
  - pip:
      - ConfigArgParse==0.15.1
      - dataclasses-json==0.2.7
      - dacite
