name: kafka-utils-test
channels:
  - conda-forge
  - defaults
dependencies:
  - kafka-python 1.4.*
  - pip
  - pip:
      - ConfigArgParse
      - pytest
      - pytest-mock
      - dataclasses-json
      - pytest-cov
      - flake8