name: anubis-cron-job
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.7.*
  - kafka-python 1.4.6
  - jsonschema >= 3.0.2
  - pip
  - pip:
    - dacite
    - ConfigArgParse==0.15.1
    - python-crontab >= 2.3
    - dataclasses-json==0.2.7
    - flake8-black
