bases:
  - @@STAGE@@
images:
  - name: benchmarkai/executor
    newName: @@DOCKER_IMAGE_TAG@@
configMapGenerator:
  - name: executor
    literals:
      - transpiler_puller_docker_image=@@PULLER_DOCKER_IMAGE_TAG@@
      - transpiler_metrics_pusher_docker_image=@@METRICS_PUSHER_DOCKER_IMAGE_TAG@@
      - transpiler_metrics_extractor_docker_image=@@METRICS_EXTRACTOR_DOCKER_IMAGE_TAG@@
      - transpiler_cron_job_docker_image=@@CRON_JOB_DOCKER_IMAGE_TAG@@
      - transpiler_job_status_trigger_docker_image=@@JOB_STATUS_TRIGGER_DOCKER_IMAGE_TAG@@
    behavior: merge
