apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-benchmark
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-manager
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods/log", "pods/status", "pods", "services"]
  verbs: ["get", "delete", "create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inference-benchmark-pod-manager-binding
subjects:
- kind: ServiceAccount
  name: inference-benchmark
  namespace: default
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: ""
