name: fetcher-job
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.7.*
  - kazoo 2.5.*
  - boto3 1.9.*
  - python-kubernetes 9.0.*
  - pycurl 7.43.*
  - retrying 1.3.*
  - pip
  - pip:
    - ConfigArgParse
    - dataclasses-json
