name: executor
channels:
  - conda-forge
  - defaults
dependencies:
  - python 3.7.*
  - ruamel.yaml >= 0.15
  - setuptools == 41.0.1
  - toml 0.9.*
  - addict 2.2.*
  - python-kubernetes 9.0.*
  - python-crontab >= 2.3
  - flake8
  - kafka-python 1.4.6
  - jsonschema >= 3.0.2
  - pip
  - pip:
    - ConfigArgParse==0.15.1
    - dataclasses-json==0.2.7
    - dacite
