# Example service account, role, and role binding
# with minimal required authorizations
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-extractor
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-log
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-extractor-pod-log-binding
subjects:
- kind: ServiceAccount
  name: metrics-extractor
  namespace: default
roleRef:
  kind: Role
  name: pod-log
  apiGroup: ""
