{
 "title": "Operational metrics by Action ID",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
   },
   {
    "name": "client_id",
    "label": "Client ID",
    "query": "label_values(kube_pod_labels, label_client_id)"
   },
   {
    "name": "action_id",
    "label": "Action ID",
    "query": "label_values(kube_pod_labels{label_client_id=\"$client_id\"}, label_action_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_fs_writes_bytes_total[1m]) * \n        on (pod_name) group_left(label_action_id, label_client_id) \n        label_replace(kube_pod_labels{label_action_id=\"$action_id\",label_client_id=\"$client_id\"},\"pod_name\",\"$1\",\"pod\",\"(.*)\"))\nby (label_action_id)"
    },
    {
     "expr": "sum (rate(container_fs_reads_bytes_total[1m]) * \n        on (pod_name) group_left(label_action_id, label_client_id) \n        label_replace(kube_pod_labels{label_action_id=\"$action_id\",label_client_id=\"$client_id\"},\"pod_name\",\"$1\",\"pod\",\"(.*)\"))\nby (label_action_id)"
    }
   ]
  },
  {
   "title": "GPU MemCpy Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dcgm_mem_copy_utilization{job=\"gpu_metrics\"} * \n  on (pod_name) group_left(label_action_id, label_client_id) \n  label_replace(kube_pod_labels{label_action_id=\"$action_id\",label_client_id=\"$client_id\"},\"pod_name\",\"$1\",\"pod\",\"(.*)\")\n"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m]) * \n        on (pod_name) group_left(label_action_id, label_client_id) \n        label_replace(kube_pod_labels{label_action_id=\"$action_id\",label_client_id=\"$client_id\"},\"pod_name\",\"$1\",\"pod\",\"(.*)\"))\nby (label_action_id)"
    }
   ]
  },
  {
   "title": "GPU Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "dcgm_fb_used{job=\"gpu_metrics\"} *\n  on (pod_name) group_left(label_action_id, label_client_id) \n  label_replace(kube_pod_labels{label_action_id=\"$action_id\",label_client_id=\"$client_id\"},\"pod_name\",\"$1\",\"pod\",\"(.*)\")\n"
    }
   ]
  },
  {
   "title": "GPU Core Utilitization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dcgm_gpu_utilization{job=\"gpu_metrics\"} * \n        on (pod_name) group_left(label_action_id, label_client_id) \n        label_replace(kube_pod_labels{label_action_id=\"$action_id\",label_client_id=\"$client_id\"},\"pod_name\",\"$1\",\"pod\",\"(.*)\")\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container_name='benchmark'} *\n  on (pod_name) group_left(label_action_id, label_client_id) \n  label_replace(kube_pod_labels{label_action_id=\"$action_id\",label_client_id=\"$client_id\"},\"pod_name\",\"$1\",\"pod\",\"(.*)\")"
    }
   ]
  }
 ]
}