# BenchmarkAI meta
spec_version = "0.1.0"

# These fields don't have any impact on the job to run, they contain
# merely informative data so the benchmark can be categorized when displayed
# in the dashboard.
[info]
task_name = "Example single node benchmark"
description = """ \
    An example single node benchmark, running image classification on the MNIST dataset \
    using ResNet50 on MXNet. \
    """

# 1. Hardware
[hardware]
instance_type = "p3.8xlarge"
strategy = "single_node"

# 2. Environment
[env]
# Docker hub <hub-user>/<repo-name>:<tag> 
docker_image = "jlcont/benchmarking:070419"

# 3. Machine learning related settings: 
# dataset, benchmark code and parameters it takes
[ml]
benchmark_code = "python3 /home/benchmark/image_classification.py --model=resnet50_v2 --batch-size=32 --gpus=4"

# [Opt] 4. Dataset 
[data]
# Dataset ID
id = "mnist"
# md5 = "rddytftyfrdr75657fftrtrt11"

# [Opt] Data sources
# List all required data sources below. 
# Make an entry for each with the same format as the ones below.
[[data.sources]]
# Data download URI.
src = "s3://mlperf-data-mxnet-berlin/mnist"
# Path where the dataset is stored in the container FS
path = "/data/mnist"

# ...

# 4. Output
[output]
# Define which metrics will be tracked in this benchmark
metrics = ["accuracy"]
