version: 0.2

phases:
  build:
    commands:
      - env
      - export KUBECONFIG=${CODEBUILD_SRC_DIR_infra_output}/kubeconfig
      - cd ${PROJECT_NAME}
      - make deploy STAGE=prod COMMIT_SHORT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION} VERSION=latest DOCKER_REGISTRY=${DOCKER_REGISTRY}
