version: 0.2

phases:
  install:
    commands:
      - conda create --yes -c conda-forge -p /opt/deploy kubernetes awscli
      - export PATH=/opt/deploy/bin:$PATH
  pre_build:
    commands:
      - aws eks update-kubeconfig --kubeconfig /tmp/kubeconfig --name benchmark-cluster
      - export KUBECONFIG=/tmp/kubeconfig
  build:
    commands:
      - ls
      - |
        if [ -f "deploy.yml" ] && [ $(stat --printf="%s" deploy.yml) -gt 0 ]; then
          cat deploy.yml
          kubectl apply -f deploy.yml
        elif [ -f "deploy/stage_deploy.sh" ]; then
          bash deploy/stage_deploy.sh prod
        else
          echo "Nothing to deploy"
        fi
