version: 0.2

phases:
  install:
    commands:
    # kubernetes 1.14 is a part of the base image - no need to install it here
      - conda create --yes -c conda-forge -p /opt/deploy awscli
      - export PATH=/opt/deploy/bin:$PATH
  pre_build:
    commands:
      - aws eks update-kubeconfig --kubeconfig /tmp/kubeconfig --name benchmark-cluster
      - export KUBECONFIG=/tmp/kubeconfig
  build:
    commands:
      - ls
      - |
        if [ -f "deploy.yml" ]; then
          if  [ $(stat --printf="%s" deploy.yml) -gt 0 ]; then
            echo "Deploying with `deploy.yml` file"
            cat deploy.yml
            kubectl apply -f deploy.yml
          else
            echo "The file `deploy.yml` exists but is empty. Assuming there is nothing to deploy."
          fi
        elif [ -f "deploy/kustomization.yml" ]; then
          echo "Deploying with `deploy/kustomization.yml`. The contents are:"
          cat deploy/kustomization.yml
          kubectl apply -k deploy
        else
          echo "Artifacts to deploy were not created. Erroring!"
          echo "PWD=$(pwd)"
          env
          exit 1
        fi
