version: 0.2

phases:
  install:
    commands:
      - curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      - bash Miniconda3-latest-Linux-x86_64.sh -b
      - export PATH=$PATH:/root/miniconda3/condabin
    runtime-versions:
      docker: 18
  build:
    commands:
      - env
      - mkdir -p build
      - DOCKER_REGISTRY=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - cd ${PROJECT_NAME}
      - make deploy.yml STAGE=prod COMMIT_SHORT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION} VERSION=latest DOCKER_REGISTRY=${DOCKER_REGISTRY}
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - make publish COMMIT_SHORT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION} VERSION=latest DOCKER_REGISTRY=${DOCKER_REGISTRY}
      # Move built files to the root `build` directory since that's the directory that gets packaged
      - cp -r ${PROJECT_NAME}/deploy* ../build/
artifacts:
  files:
    - deploy.yml
    - deploy/**/*
  discard-paths: no
  base-directory: build