version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - env
      - cd ${PROJECT_NAME}
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - make publish COMMIT_SHORT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION} VERSION=latest DOCKER_REGISTRY=${DOCKER_REGISTRY}
