version: 0.2

phases:
  install:
    commands:
    # kubernetes 1.14 is a part of the base image - no need to install it here
      - conda create --yes -c conda-forge -p /opt/deploy awscli
      - export PATH=/opt/deploy/bin:$PATH
  pre_build:
    commands:
      - aws eks update-kubeconfig --kubeconfig /tmp/kubeconfig --name benchmark-cluster
      - export KUBECONFIG=/tmp/kubeconfig
  build:
    commands:
      - ls -la
      - env
      - cd ${PROJECT_NAME}
      - make deploy STAGE=prod COMMIT_SHORT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION} VERSION=latest DOCKER_REGISTRY=${DOCKER_REGISTRY} || echo "New deploy failed :)"
