version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - env
      - cd ${PROJECT_NAME}
      # HACK since pipeline does not treat repository as a git tree
      - if [ "${PROJECT_NAME}" = "bai-bff" ]; then export VERSION=$(cat bin/anubis | grep VERSION= | cut -d \" -f2); fi
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - make publish COMMIT_SHORT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION} DOCKER_REGISTRY=${DOCKER_REGISTRY}
