apiVersion: v1
kind: ServiceAccount
metadata:
  name: watcher
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watcher
  namespace: default
rules:
- apiGroups: ["","batch"]
  resources: ["jobs/status"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watcher-pod-status-binding
subjects:
- kind: ServiceAccount
  name: watcher
  namespace: default
roleRef:
  kind: Role
  name: watcher
  apiGroup: rbac.authorization.k8s.io
