transpiler-puller-mount-chmod: 777
transpiler-puller-docker-image: benchmarkai/puller:3115770
transpiler-cron-job-docker-image: benchmarkai/anubis-cron-job:3115770

# descriptor config
transpiler-valid-strategies: single_node,horovod

transpiler-metrics-pusher-docker-image: benchmarkai/metrics-pusher:ffed580
# Include empty string as a valid value
transpiler-valid-frameworks: tensorflow,mxnet,