# Example service account, role, and role binding
# with minimal required authorizations
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inference-benchmark
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["jobs/status"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["", "batch"]
  resources: ["jobs", "pods", "services"]
  verbs: ["delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: inference-benchamrk-role-binding
subjects:
- kind: ServiceAccount
  name: metrics-pusher
  namespace: default
roleRef:
  kind: Role
  name: inference-benchmark
  apiGroup: rbac.authorization.k8s.io
