apiVersion: v1
kind: ConfigMap
data:
  consumer_group_id: fetcher-dispatcher
  consumer_topic: BAI_APP_BFF
  producer_topic: BAI_APP_FETCHER
  status_topic: BAI_APP_STATUS
  job_node_selector: '{"node.type":"bai-services-network"}'
  job_image: benchmarkai/fetcher-job
  pull_policy: Always
  min_volume_size: 65536
  storage_class: ""
metadata:
  name: fetcher-dispatcher
  namespace: default
