version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
#  pre_build:
#    commands:
#      -
  build:
    commands:
      - cd client-lib
      - conda env create -f test-environment.yml -n client-lib
      - conda run -n client-lib python setup.py install
      - conda run -n client-lib tox
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths