apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: fetcher-dispatcher
          imagePullPolicy: Never
      affinity:
      #--
      nodeSelector:
      #--

