apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-dispatcher
spec:
  template:
    spec:
      containers:
        - name: fetcher-dispatcher
          imagePullPolicy: Never
      affinity:
      #--
      nodeSelector:
      #--

